# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to Staging

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: "figlet"
          environment_name: "Figlet-env"
          region: "us-west-2"
          version_label: "Figlet-env-${{ github.sha }}"
          deployment_package: ./deploy.zip
          use_existing_version_if_available: true

      - name: Deployed!
        run: echo App deployed to ELB